module ICU4X
  VERSION: String

  class Error < StandardError
  end

  class LocaleError < Error
  end

  class DataError < Error
  end

  class DataGeneratorError < Error
  end

  class DataProvider
    def self.from_blob: (Pathname path, ?priority: :language | :region) -> DataProvider
  end

  class DataGenerator
    def self.export: (locales: Array[String], markers: Symbol | Array[String], format: Symbol, output: Pathname) -> void
    def self.available_markers: () -> Array[String]
  end

  class Locale
    def self.parse: (String locale_str) -> Locale
    def self.parse_posix: (String posix_str) -> Locale

    def language: () -> String?
    def script: () -> String?
    def region: () -> String?
    def extensions: () -> { unicode: Hash[String, String], transform: String?, private: Array[String] }
    def to_s: () -> String
    def inspect: () -> String
    def ==: (Locale other) -> bool
    def eql?: (Locale other) -> bool
    def hash: () -> Integer
  end

  type plural_category = :zero | :one | :two | :few | :many | :other
  type plural_rule_type = :cardinal | :ordinal

  class PluralRules
    def self.new: (Locale locale, provider: DataProvider, ?type: plural_rule_type) -> PluralRules

    def select: (Integer | Float number) -> plural_category
    def categories: () -> Array[plural_category]
    def resolved_options: () -> { locale: String, type: plural_rule_type }
  end

  type number_format_style = :decimal | :percent | :currency
  type rounding_mode = :ceil | :floor | :expand | :trunc | :half_ceil | :half_floor | :half_expand | :half_trunc | :half_even

  type date_style = :full | :long | :medium | :short
  type time_style = :full | :long | :medium | :short

  class NumberFormat
    def self.new: (
      Locale locale,
      provider: DataProvider,
      ?style: number_format_style,
      ?currency: String,
      ?use_grouping: bool,
      ?minimum_integer_digits: Integer,
      ?minimum_fraction_digits: Integer,
      ?maximum_fraction_digits: Integer,
      ?rounding_mode: rounding_mode
    ) -> NumberFormat

    def format: (Integer | Float | BigDecimal number) -> String
    def resolved_options: () -> {
      locale: String,
      style: number_format_style,
      use_grouping: bool,
      ?currency: String,
      ?minimum_integer_digits: Integer,
      ?minimum_fraction_digits: Integer,
      ?maximum_fraction_digits: Integer,
      ?rounding_mode: rounding_mode
    }
  end

  class DateTimeFormat
    def self.new: (
      Locale locale,
      provider: DataProvider,
      ?date_style: date_style,
      ?time_style: time_style,
      ?time_zone: String,
      ?calendar: Symbol
    ) -> DateTimeFormat

    def format: (Time time) -> String
    def resolved_options: () -> {
      locale: String,
      calendar: Symbol,
      ?date_style: date_style,
      ?time_style: time_style,
      ?time_zone: String
    }
  end
end
