module ICU4X
  VERSION: String

  class Error < StandardError
  end

  class LocaleError < Error
  end

  class DataError < Error
  end

  class DataGeneratorError < Error
  end

  class DataProvider
    def self.from_blob: (Pathname path, ?priority: :language | :region) -> DataProvider
  end

  class DataGenerator
    def self.export: (locales: Array[String], markers: Symbol | Array[String], format: Symbol, output: Pathname) -> void
    def self.available_markers: () -> Array[String]
  end

  class Locale
    def self.parse: (String locale_str) -> Locale

    def language: () -> String?
    def script: () -> String?
    def region: () -> String?
    def extensions: () -> { unicode: Hash[String, String], transform: String?, private: Array[String] }
    def to_s: () -> String
    def inspect: () -> String
    def ==: (Locale other) -> bool
    def eql?: (Locale other) -> bool
    def hash: () -> Integer
  end

  type plural_category = :zero | :one | :two | :few | :many | :other
  type plural_rule_type = :cardinal | :ordinal

  class PluralRules
    def self.new: (Locale locale, provider: DataProvider, ?type: plural_rule_type) -> PluralRules

    def select: (Integer | Float number) -> plural_category
    def categories: () -> Array[plural_category]
    def resolved_options: () -> { locale: String, type: plural_rule_type }
  end
end
